- scylla-artifacts.py
> scylla-artifacts: Add scylla logs checking

- scylla-artifacts.py
> scylla-artifacts.py: Add scylla-io-setup.service logs

- scylla-artifacts.py
> Fix repo setup command

- scylla-artifacts.py
Signed-of-by: Benoît Canet <benoit@scylladb.com>
> cassandra-stress: Reducing c-s load

- scylla-artifacts.py
> scylla-artifacts.py: Fix incorrect write command

- scylla-artifacts.py
> scylla-artifacts.py: Another fix to the c-s command line

- scylla-artifacts.py
> scylla-artifacts.py: Add Ubuntu 16.04 to the list of supported distros

- scylla-artifacts.py
> scylla-artifacts.py: Do not use sudo param on process.run()

- scylla-artifacts.py
Feature to detect RPM scriptlet failures and fail the test, afterwards all other testing is done (running nodetool and cassandra-stress).
> Scriptlet failure detection

- scylla-artifacts.py
Make sure package refresh (apt-get update) actually returns
0 before running 'apt-get upgrade'. This way we're giving
time to eventual background package update services to run.
Do that custom handling by defining a custom AptBackend in
the test and overriding the 'upgrade' function accordingly.
> Apt-get distros: Fix problem with background processes

- scylla-artifacts.py
Update repo/package info of Ubuntu 14.04 & centos 7.
> Pkg info update (1.3, 1.4, 1,5)

- scylla-artifacts.py
We supported both Ubuntu and Debian now, and Ubuntu is one of
Debian variant, so `debian` is better naming.
This patch also added support for debian8.
> support debian 8

- scylla-artifacts.py
This patchset moved report function to base class of installer: ScyllaInstallGeneric
> cleanup: move try_report_uuid() to ScyllaInstallGeneric

- scylla-artifacts.py
Enhanced network was enabled by https://github.com/scylladb/scylla/commit/33309f66
This patch verifies the enhanced network is enabled in AMI instances by
checking the driver name.
Reference:
https://github.com/scylladb/scylla/commit/b8f40a2d
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html#enabling_enhanced_networking
> AMI: verify that enhanced network is enabled

- scylla-artifacts.py
We just added a second disks to test vms for raid setup,
this patch adjusted raid option and disable cpuscaling
setup for a known issue [1] will cause full setup fails.
[1] https://github.com/scylladb/scylla/issues/2051
> fix raid setup and disable cpuscaling setup

- scylla-artifacts.py
This patch verified scylla setup works.
> artifacts: verify scylla setup

- scylla-artifacts.py
- scylla_private_repo.py
- scylla_private_repo.yaml
Useful repo can be got from private link.
Verify redirection works.
Verify download info can be collected to housekeeping db.
> artifact-test: add private repo test

- scylla-artifacts.py
Cleanup release mode and re-support enterprise inside ci mode.
Fixes: https://github.com/scylladb/scylla-artifact-tests/issues/68
> simply support enterprise inside ci mode

- scylla-artifacts.py
Test job:  
http://jenkins.cloudius-systems.com/job/scylla-2.0-ami-i3-test/14/
http://jenkins.cloudius-systems.com/job/scylla-2.0-ami-i3-test/15/
> always ouput io/cpuset/cpu affinity config

- scylla-artifacts.py
The hardware (cpu/mem) of fixed instance type is fixed, so cpuset and io config should be fixed.
Current cpuset and io config results:
> strict checking for cpuset and io config

- scylla-artifacts.py
This is for master & branch-2.1
> enable extend repo for installing scylla

- scylla-artifacts.py
- scylla_private_repo.py
It might touch 301 error in downloading the private repo without '-L' option.
> append -L to curl cmdline

- scylla-artifacts.py
This reverts commit b40c815a6b67e65a0a1a4922c853a628f0fda418.
In scylla-master-centos-rpm-test, Avocado won't copy scylla_private_repo.py
to vm, it will reach an ImportError. Let's revert this patch first.
Signed-off-by: Amos Kong <amos@scylladb.com>
> Revert "verify download private repo"

- scylla-artifacts.py
Raise error when housekeeping.uuid doesn't exist
> add assert for housekeeping.uuid

- scylla-artifacts.py
remove workaround for ubuntu14
> workaround restart hkeeping issue of debian8

- scylla-artifacts.py
Test job link [job/scylla-staging-ubuntu-deb-18.04-test-clone/1](http://jenkins.cloudius-systems.com:8080/job/scylla-staging-ubuntu-deb-18.04-test-clone/1/)
> support ubuntu 18.04

- scylla-artifacts.py
Scylla_setup issue might block the test, set a timeout for it.
> add timeout for executing scylla_setup

- scylla-artifacts.py
> try to catch scylla_prepare/irq setting error

- scylla-artifacts.py
Old key has expired and we need to update it for master and 3.2.
> Replace signed packages signed gpg key with a new one

- requirements-python.txt
Known security vulnerabilities detected.
CVE-2017-18342 High severity
Signed-off-by: Amos Kong <amos@scylladb.com>
> update the PyYAML version for security
