scylladb/scylla-artifact-tests

- scylla-artifacts.py
Sometimes we might run on slow disks, so let's unconditionally
skip the iotune setup process and use the most conservative
settings possible, at least for now.
> scylla-artifacts.py: Adjust io settings before the test

- scylla-artifacts.py
Instead of relying on python, let's use a sudo one liner
to install the scylla repository in our box (that's to help
with the AMI test).
> scylla-artifacts.py: Use a sudo friendly repo install command

- scylla-artifacts.py
Let's use tee instead of shell redirection. Also, this is only
needed on non-AMI testing.
> scylla-artifacts.py: Fix problem with scylla io setup command

- scylla-artifacts.py
Since now with iotune the startup time is a lot longer than
what it used to be.
> scylla-artifacts.py: Increase the timeout for scylla DB to be up

- scylla-artifacts.py
We can't afford to wait 1 hour by default to see if scylla
server is up.
> scylla-artifacts.py: Reduce wait for scylla service

- scylla-artifacts.py
Those are the real errors we should be paying attention to.
> scylla-artifacts.py: Catch java IO Errors during c-s execution

- scylla-artifacts.py
Let's use an uniform key distribution to avoid the mixed workload
not finding the right keys.
> scylla-artifacts.py: Use uniform key distribution on mixed workload

- scylla-artifacts.py
- scylla-artifacts.py.data/scylla-artifacts.yaml
The current version of the test is cluttered and could
use some logical separation of code responsible for
installing Scylla and actual test of the installed artifacts.
So let's do that by splitting the code into installers,
service managers and the test itself. This also updates
the release mode testing to use the new repository files
for Fedora, CentOS and Ubuntu.
> scylla-artifacts.py: Refactor package install code

- scylla-artifacts.py
Ubuntu may sometimes have a background apt upgrade thread,
causing the test triggered update to not work. Let's keep
trying every 30 seconds until the .upgrade() method returns
True, this will give the background thread time to finish.
> scylla-artifacts.py: Wait until system upgrade is actually done

- scylla-artifacts.py
We use uuid to identify each Scylla db node,
this patch reports uuid of test node to ScyllaDB,
it helps to identify real users.
> report uuid of test node to ScyllaDB

- scylla-artifacts.py
uuid generation is moved to scylla-housekeeping script,
we have to wait the service up, then try to report the uuid.
> report uuid after service is up

- scylla-artifacts.py
ScyllaInstallAMI implemented its own run() function,
currently AMI tests still don't report uuid, this
patch supported it.
> ami: report uuid after service is up

- scylla-artifacts.py
In scylla 1.7, scylla-jmx and scylla-tools depend on openjdk packages.
This patch enables openjdk repo for install scylla 1.7 and later.
https://github.com/scylladb/scylla/issues/2091
> ubuntu 14.04: enable openjdk repo for installing scylla 1.7 and later

- scylla-artifacts.py
In scylla 1.7, scylla-jmx and scylla-tools depend on openjdk packages.
This patch enables openjdk repo for install scylla 1.7 and later.
https://github.com/scylladb/scylla/issues/2091
> ubuntu16.04/debian8: enable openjdk repo for installing scylla 1.7 and later

- scylla-artifacts.py
Only for Ubuntu 16 for now, using the "mode" parameter by transferring it via Jenkins job.
Any mode transfered different than "ci" will trigger scylla-enterprise installation.
> Adding support for scylla-enterprise installation type

- scylla-artifacts.py
Fix the problem with Travis CI and scylla-artifact-tests introduced by fd60b1f96b6d74216e5780b799a5e272676598c2.
@slivne and @roydahan, please take a look and merge at your earliest convenience.
> scylla-artifacts: Fix a few PEP8 errors

- scylla-artifacts.py
Currently we only setup scylla with scylla_io_setup script, this patch changed to execute 'scylla_setup' with all default options.
> full scylla setup

- scylla-artifacts.py
This reverts commit c10f4d7de68f35f9c340d847d3e266a6b4a970c6.
It doesn't work in raid setup on Ubuntu without XFS disk.
> Revert "full scylla setup"

- scylla-artifacts.py
Cassandra-stress might raise exception and get stuck,
it will block the whole job.
> set timeout for cassandra-stress

- scylla-artifacts.py
'--no-cpuscaling-setup' doesn't exist in 1.6, it will trigger
a deadloop bug [1] of scylla_setup script.
[1] https://github.com/scylladb/scylla/issues/2305
> only disable cpuscaling when the option exists

- scylla-artifacts.py
Sometimes scylla_setup executes good, but the service fails to start for scylla bug. Then it will repeatedly setup scylla.
Let's skip repeated raid and node_exporter setup, then the second scylla_setup won't fail.
> RFC: skip repeated raid and node_exporter setup

- scylla-artifacts.py
We use the full version info which is got from `apt-cache show scylla` for comparing. 
Sometimes the wrong in comparing version causes java8 isn't installed as expected.
Let's just compare the major part of version.
> only compare major version

- scylla_docker.py
There is an issue to run the docker run for images that aren't locally.
The run command doesn't have a silent option (yet), so when it tries to download the image, there are ugly progress bars that Jenkins doesn't like.
> redirect output of docker run to /dev/null

- libvirt-check.sh
The libvirt-check.sh is used to prepare running VM for artifact testing.
> commit libvirt-check.sh script

- scylla-artifacts.py
scylla_setup only disables SELinux on Red Hat variants, we should skip verify on ubuntu.
the second patch is for better support on debian variants.
The PR was tested in jenkins job.
> verify scylla_setup: selinux, better support for ubuntu

- scylla_private_repo.yaml
Aws backend added strict checking for the version string,
this patch corrected the urls to make the valid.
> private_repo: correct the repo urls

- scylla-artifacts.py
Doc to prepare environment:
https://github.com/scylladb/scylla-artifact-tests/wiki/support-debian9-for-scylla-artifact-tests
Problem: we don't have build for debian9 now. @slivne what's the plan?
> scylla-artifact: support debian9

- scylla-artifacts.py
Their Distro names are same.
LinuxDistro: name=redhat, version=7, release=x, arch=x86_64
> scylla-artifacts: support redhat and oel distros

- scylla-artifacts.py
Running 'sudo curl https://repositories.scylladb.com/scylla/repo/xxxx/debian/scylladb-2.0-jessie.list ...
Running 'sudo apt-get update'
[stderr] E: The method driver /usr/lib/apt/methods/https could not be found.
> apt backend: install apt-transport-https

- scylla-artifacts.py
In order to use signed packages, we need to authenticate them using “apt-key” command.
In order to make sure the test really uses the authenticated packages, we override the “—allow-unauthenticated” flag that is automatically added by avocado for AptBackend software manager.
> Use Signed artifacts

- scylla-artifacts.py
This patch added a new parameter `allow_unauth` in configure file
to control `--allow-unauthenticated` in apt cmdline.
> apt-backend: make --allow-unauthenticated configurable

- scylla_private_repo.py
There are some new parameters in scylla 2.1 repo, this patch updated
the prefix list.
Problem: New [scylla-private-repo jobs](http://jenkins.cloudius-systems.com/job/scylla-private-repo-test/label=gce3,scylla_version=scylladb-2.1/) of scylla-2.1 failed for repo checking.
[Test job](http://jenkins.cloudius-systems.com/job/scylla-private-repo-test-amos-clone/label=gce3,scylla_version=scylladb-2.1/2/console) of this PR is good.
> private-repo: add some prefix of repo content

- scylla_private_repo.yaml
Commit d5116e64dbbf178b2fcbf7158d63b111a20d5200 introduced an issue, the uuid in pkg_info isn't updated together.
> Fix hkeeping UUID in config file

- scylla-artifacts.py
Amnon already added key `id` for checkversion table, let's use it.
Test job:  [scylla-master-centos-rpm-test-clone-amos/26/](http://jenkins.cloudius-systems.com/job/scylla-master-centos-rpm-test-clone-amos/26/)
(Good)
> verify hkeeping in scylla_setup by key `id`

- scylla-artifacts.py
repoid and ruid of checkversion table aren't filled correctly by housekeeping backend (except centos)
We can revert the workaround when the issue is fixed by Amnon.
> workaround backend issue to fill ruuid/repoid of checkversion

- scylla-artifacts.py
scylla-ami-setup.service only exists in ec2 AMI instance.
housekeeping error is also useful.
Currently if scylla-ami-setup has problem, artifact-test won't catch the error log.
> dump more log relate with scylla

- scylla-artifacts.py
Collectd was dropped from scylla package, so remove the status check of collectd.
Related commit: https://github.com/scylladb/scylla/commit/9971576ecb77abc228c4f11fb6271ccb4efb5e05
> ScyllaInstallGeneric: remove collectd verify

- scylla-artifacts.py
Journalctl only shows last 10 lines by default in follow mode (-f). We need to
dump the full log. This patch added '--no-tail' option to show all lines even
in follow mode.
Problem: we can't see some scylla-ami-setup error, or early scylla_prepare error.
Bad example: http://jenkins.cloudius-systems.com:8080/job/scylla-master-ami-test/239/label=muninn/artifact/latest/job.log
Good example (test with this PR): http://jenkins.cloudius-systems.com:8080/job/scylla-staging-ami-test-clone/1/label=muninn/1/
> journalctl: dump the full log

- scylla-artifacts.py
On ubuntu 18.04 & debian 9, the Enternet network device name is `ens0`.
The hardcode name doesn't work.
> detect network device name before setup

- scylla-artifacts.py
The io.conf setup is changed from 2.3, the properties is moved to
/etc/scylla.d/io_properties.yaml
> ami: update verify of io.conf

- scylla-artifacts.py
We don't need to wait until timeout if some db error occurs,
it's waste of test time and resource, just fail the test.
fix #107
> check error in waiting the server to up

- scylla-artifacts.py
scylla-jmx doesn't work with latest jdk.
related issue: https://github.com/scylladb/scylla/issues/3858
> use java 1.8 on ubuntu 18.04

- scylla-artifacts.py.data/scylla-docker.yaml
- scylla_docker.py
If host is busy or slow, scylla in docker container start slowly
and tests in scylla_docker.py are failed by timeout which is 30
Addint to configuration and possiblity to customize this timeout:
- in yaml file scylla-docker.yaml 'timeupwait'
- adding parameter to ScyllaDocker
Addintionally, tests failed due error on parsing output:
> Op rate                   :   18,589 op/s  [READ: 18,589 op/s]
> Partition rate            :   18,589 pk/s  [READ: 18,589 pk/s]
with exception
_ERROR| Failed parsing stress results: Op rate:   11,779 op/s  [WRITE: 11,779 op/s], error: invalid literal for float(): 11,779_
Adding code to cut the ',' from parsed value.
> Adding parameter timeout for waiting cluster up

- scylla_docker.py
Clean cluster if cluster isn't up.
Tested PR in muninn:
```
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
JOB HTML   : /root/avocado/job-results/job-2018-11-29T14.16-41fca17/html/results.html
TESTS TIME : 387.40 s
avocado.test: Test results available in /root/avocado/job-results/job-2018-11-29T14.16-41fca17
```
> Scylla docker fix

- scylla-artifacts.py
Current:
$ journalctl .... --since 2018-12-25 07:29:05
Failed to add match '07:29:05': Invalid argument
Failed to add filters: Invalid argument
> journalctl: wrap time of since argument

- scylla-artifacts.py
`jessie-backports` `jessie-updates` had been removed from debian source,
apt-get update / upgrade will fail.
reference:
- https://wiki.debian.org/LTS/Using
- https://wiki.debian.org/StableUpdates
> fix source issue of debian 8

- scylla_docker.py
Handle a case when c-s summary contain empty line. latest c-s version 3.11
changed its output.
Fixes #123
> scylla_docker: ignore empty line in c-s summary

- scylla_private_repo.py
I just added `2019.1` test to http://jenkins.scylladb.com/job/scylla-enterprise-private-repo-test/, but job failed for new supported distros in 2019.1 (ubuntu1804 & debian9)
> support new distros - ubuntu1804 and debian9

- install-prereqs.sh
- requirements-python.txt
added `git` and `python-devel` to prereqs
Errors that had when creating Docker container:
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting https://github.com/amoskong/avocado-ec2.git
Downloading https://github.com/amoskong/avocado-ec2.git
ERROR: Cannot unpack file /tmp/pip-unpack-Osy7yh/avocado-ec2.git (downloaded from /tmp/pip-req-build-C3ceum, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-C3ceum
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be …
```
> Updated project requirements

- scylla-artifacts.py
Original error:
scylla_prepare[13698]: Failed to write into /proc/irq/333/smp_affinity:
(<class 'OSError'>, OSError(5, 'Input/output error'), <traceback object at 0x7f636fffeec8>)
New error format:
scylla_prepare[15588]: Setting mask 00000001 in /proc/irq/90/smp_affinity:
failed to write into /proc/irq/90/smp_affinity:
(<class 'OSError'>, OSError(5, 'Input/output error'), <traceback object at 0x7fb07bb15048>)
Related old issue: https://github.com/scylladb/scylla-artifact-tests/issues/118
> update scylla_prepare/irq setting error

- scylla_docker.py
In latest test, the docker images parameter should not be included by double
quotation mark.
[amos@amos-centos7 ~]$ docker --version
Docker version 19.03.2, build 6a30dfc
[amos@amos-centos7 ~]$ docker images -f "dangling=true" -q
19c06d75f7f1
a8468ecc3d6c
[amos@amos-centos7 ~]$ docker rmi "19c06d75f7f1 a8468ecc3d6c"
Error response from daemon: invalid reference format
[amos@amos-centos7 ~]$ docker rmi --help
Usage:	docker rmi [OPTIONS] IMAGE [IMAGE...]
Remove one or more images
Options:
-f, --force      Force removal of the image
--no-prune   Do not delete untagged parents
[amos@amos-centos7 ~]$ docker rmi 19c06d75f7f1 a8468ecc3d6c
Deleted: sha256:a8468ecc3d6cfca1ff3274319990ae9f81c2fea078a060f15e38bae2d02ffcc8
Deleted: sha256:ec8a6aad2b31819afbda51b41301b4021c147324f08f569c1e76e4bf3e558d1 …
> refix clean of multiple old images

- scylla_docker.py
According to discuss in https://github.com/scylladb/scylla/issues/5096#issuecomment-534942224 , we need to start c-s workload when cqlsh is available.
> scylla_docker: add wait for cql server

- scylla-artifacts.py
This reverts commit c163409ee5849fff2bc6453fe70eb8bbca4d32fc.
The openjdk dependency of scylla-tools-java had been changed from
default-jre-headless to openjdk-8-jre-headless, then openjdk-8 (Java 1.8)
will be installed during scylla installation.
Let's revert this commit, and make sure dependency is installed successfully.
Otherwise, some bug might be hidden.
> Revert "use java 1.8 on ubuntu 18.04"

- scylla-artifacts.py
The option '--allow-unauthenticated' is no longer needed and supported.
> apt: remove unsupported option '--allow-unauthenticated'

- scylla_docker.py
Some test failed and left stopped container, their images won't be
deleted directly. We can't forcely clean them in scylla docker test,
and our test should continue.
Fixes #140
> docker: don't fail the test for exception in cleaning old images
